### ISSUE TITLE
#include <avr/eeprom.h> breaks on linux, needs backslash instead

### ISSUE THREAD

**Issue by nosliwneb** [Megunolink/ArduinoCrashMonitor#1]
also the comment form on your website breaks when you paste ```#include <avr/eeprom.h>``` into it and attempt to submit a comment (from Linux/iceweasel)

**Comment by PaulMartinsen** [comment]
Sorry; we don't use Linux. I read here that Linux uses a / to separate paths and we had #include <avr\eeprom.h> in ArduinoCrashMonitor.cpp. 

So I think you wanted me to change that to #include <avr/eeprom.h> which I've now done. 

Thanks for spotting this. 
paul
