### ISSUE TITLE
[Help] How to "clear" log

### ISSUE THREAD

**Issue by m-elias** [Megunolink/ArduinoCrashMonitor#4]
How would you "clear" the log? I'm thinking only the headers need clearing?

**Comment by PaulMartinsen** [comment]
Easiest way would be something like:
void CCrashReport::Clear()
{
  CApplicationMonitorHeader Header;
  Header.m_uSavedReports = 0;
  Header.m_uNextReport = 0;
  SaveHeader(Header);
}

**Comment by m-elias** [comment]
I just had to change it to
void CwdtLog::Clear()
{
  CwdtLogHeader Header;
  Header.m_uSavedReports = 0;
  Header.m_uNextReport = 0;
  SaveHeader(Header);
}
and it works!
Thanks!
